### ISSUE TITLE
feature: Add CursorLineNr bg color

### ISSUE THREAD

**Issue by leokang94** [svampkorg/moody.nvim#11]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

Nope. Just wanted.

### Describe the solution you'd like

I would like to below.
```lua
opts = {
  bg_nr = true -- default : false.. maybe? also, I named the options randomly. :>
}
```

### Describe alternatives you've considered

When using this option, I think it would be nice to optionally apply a blended bg color like `CursorLine` to the bg of `CursorLineNr` as well, due to the added area in the `config.lua > cache_colors_setup_highlighs` function.

```lua
vim.api.nvim_set_hl(M.ns_normal, "CursorLineNr", { fg = M.options.hl_unblended.normal, bold = M.options.bold_nr })

-- when bg_nr is true, additional set the bg color
if (M.options.bg_nr) then
  vim.api.nvim_set_hl(M.ns_normal, "CursorLineNr", { bg = M.options.hl_blended.normal })
end
```
(I'm not familiar with the lua, so... I don't know if there is a more concise syntax.)

### Additional context

When I temporarily set it up myself, it looks like this. (yes, I changed blend)
![image](https://github.com/user-attachments/assets/406a7c22-f21e-4d3b-8831-047efac18a89)
![image](https://github.com/user-attachments/assets/f4848831-2036-40e7-9051-5a790f2f6e88)
![image](https://github.com/user-attachments/assets/dfd06d4f-8325-4ff7-b052-5bbbc6dc155c)

**Comment by svampkorg** [comment]
Hello! Thanks for using my plugin 👍  I think this is a great addition, and I will start working on it as soon as I find time!

**Comment by svampkorg** [comment]
Just wanted to update you on this linenumber-background suggestion. I'm low-key working on it in between work :) 
![Screenshot 2024-11-01 at 07 34 37](https://github.com/user-attachments/assets/55a4de3b-75cd-4ff5-8006-bead359b0d80)

Just had to do some acrobatics to have my custom fold column also use the same background as the cursorline. And now I'm also thinking.. hey, maybe the line numbers should all get highlighted when making a selection. This means I'll maybe have to include the whole custom signcolumn-thing I've got going, with the signs, numbers and folds :P

Or maybe I'll just leave it as is and merge with main.. we'll see. I'll try to have it done this weekend anyway :)

**Comment by leokang94** [comment]
I hadn't thought about the fold or the additional symbols, but I like the direction you're going in, thanks!

**Comment by svampkorg** [comment]
Thanks to this commit https://github.com/neovim/neovim/commit/433b342baa04b35fb1ab24d4ef38f126d12ea714 I can finally make this change to my plugin, and have also the sign columns inherit the hl group set by Moody :)

Sorry for the long wait. Been really busy with work! I won't make a promise to have a PR ready next week, but who knows. Anything can happen! :^)

**Comment by svampkorg** [comment]
I just merged some changes which will make this possible. Closing this. Also, happy holidays!
