### ISSUE TITLE
bug: Highlight disappears when changing buffers

### ISSUE THREAD

**Issue by dvd42** [svampkorg/moody.nvim#3]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-3335+gf69937fdb-Homebrew

### Operating system/version

MacOS 

### Describe the bug

Thanks for this plugin! I am loving it so far. However, I am having the following problem:

Whenever I change buffers the highlight disappears until I change modes. I've attached a GIF showing this.

![REC-20240726173232](https://github.com/user-attachments/assets/cbdc98e6-78ef-4225-9ef9-ddbaf4cdb3a0)

Here is the config I am using:

```    
{
    "svampkorg/moody.nvim",
    event = { "ModeChanged", "BufWinEnter", "WinEnter" },
    opts = {
        blends = {
            normal = 0.2,
            insert = 0.2,
            visual = 0.25,
            command = 0.2,
            operator = 0.2,
            replace = 0.2,
            select = 0.2,
            terminal = 0.2,
            terminal_n = 0.2,
        },
        disabled_filetypes = { "TelescopePrompt" },
        bold_nr = true,
        recording = {
            enabled = true,
            icon = "󰑋",
            -- you can set some text to surround the recording registry char with
            -- or just set one to empty to maybe have just one letter, an arrow
            -- perhaps! For example recording to q, you could have! "󰑋    q" :D
            pre_registry_text = " ",
            post_registry_text = "",
        },
      },
    },
```

### Steps To Reproduce

See Video

### Expected Behavior

It's not a big deal but I suppose the expected behaviour is for the highlight to remain when switching buffers

**Comment by svampkorg** [comment]
Hey! Thanks for letting me know about this. I will look into it as soon as I’m back from Holliday tomorrow! :)

**Comment by svampkorg** [comment]
Accidentally closed this…

**Comment by svampkorg** [comment]
@dvd42 I tried the same bufferline, and lualine config from your dotfiles, to see if any of those plugins would affect the way Moody works. Also tried kickstart.nvim with it's plugins, and Moody. The highlights persisted on buffer change.

Could there be other plugins you have, with events for WinEnter and BufWinEnter, which are changing the CursorLine? Or do you have any of your own autocommands on those events?

Are you changing buffer with :bn, or what's the command you are entering? The video was a little blurry here so couldn't quite see 8) If you have time, could you try running neovim with just Moody installed, and see if the highlights persist or not?

**Comment by dvd42** [comment]
Hey @svampkorg thanks for looking into this.

 Yes, I am changing the buffer with :bn. The only plugin I have that interacts with buffers is barbar.nvim, which I use to handle my buffers, however disabling that does not help. I have no autocommands on those events.
 
 I can confirm that the highlight persists with a minimal config using just Moody. I'll try to find the culprit and report back. Thanks!

**Comment by dvd42** [comment]
Hey @svampkorg I looked into it, it was this line I had inside one of my config files:

vim.cmd(':set winhighlight=' .. cmp.config.window.bordered().winhighlight)


Sorry for the noise and thanks for looking into it. I'll close this now
