### ISSUE TITLE
[BUG]: Line Highlighting only functions in the first launch of moody installation and not future launches using NvChad

### ISSUE THREAD

**Issue by ianTevesAcc** [svampkorg/moody.nvim#5]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

Windows 11 Home 26120.1912

### Describe the bug

Moody nvim active line highlights only work when first installed and loaded, and doesn't work in later launches of neovim. I use NVchad and I've tried setting lazy to false as well as setting highlights as on and etc. to see what might be causing it to not actiavate in other launches of neovim. But I still can't figure out why the line highlighting doesn't work.

Do you have any idea what might be happening here?

https://github.com/user-attachments/assets/b7ac9972-3bec-4b1d-998a-9ad8c45eb215

### Steps To Reproduce

1. Install Nvchad
2. Create moody.lua in plugins dir
3. Place default moody config inside return {}
4. restart nvim and watch it install moody (everything works fine and moody line highlighting is active)
5. close nvim and start nvim again (line highlighting no longer works)

### Expected Behavior

moody line highlighting to still be working

**Comment by ianTevesAcc** [comment]
Im stupid.

You can add / un-comment the following at options.lua to enable cursorline.
``` lua
local o = vim.o
o.cursorlineopt ='both' 
```

**Comment by svampkorg** [comment]
Hey! Thanks for trying my plugin! And for reporting this. I should maybe add this option to the plugin itself.. 🤔

I'm glad you got it working tho'!
