### ISSUE TITLE
bug: Setting colours using `opts` doesn't work

### ISSUE THREAD

**Issue by kamack38** [svampkorg/moody.nvim#9]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

ArchLinux

### Describe the bug

![image](https://github.com/user-attachments/assets/a8c7e378-aa2c-41f8-afa5-e1dd625b2d06)

Even after changing the colours to black, the displayed colours still stay the same.

There are no *Moody* highlight groups.

![image](https://github.com/user-attachments/assets/7304bf64-063a-44f1-9a51-6aa283c07e7c)

### Steps To Reproduce

Here's the config
```lua
  {
    "svampkorg/moody.nvim",
    event = { "ModeChanged", "BufWinEnter", "WinEnter" },
    opts = {
      blends = {
        normal = 0.2,
        insert = 0.2,
        visual = 0.25,
        command = 0.2,
        operator = 0.2,
        replace = 0.2,
        select = 0.2,
        terminal = 0.2,
        terminal_n = 0.2,
      },
      -- there are two ways to define colours for the different modes.
      -- one way is to define theme here in colors. Another way is to
      -- set them up with highlight groups. Any highlight group set takes
      -- precedence over any colours defined here.
      colors = {
        normal = "#000000",
        insert = "#000000",
        visual = "#000000",
        command = "#EB788B",
        operator = "#FF8F40",
        replace = "#E66767",
        select = "#AD6FF7",
        terminal = "#4CD4BD",
        terminal_n = "#00BBCC",
      },
    },
    dependencies = {
      "NvChad/base46",
    },
  },
```

### Expected Behavior

The `normal` colur should be black.

**Comment by svampkorg** [comment]
Hello! Thank you for reporting this issue! And for using my plugin =P

**I just pushed a change to main which should fix this issue. Please let me know if this helped.**

Regarding the highlight groups. They are not created by the plugin. They are for you to define in your colorscheme, like the example in the readme.  Most colorshemes has a highlight_override field where you can define your own hl groups. Make sure to set any Moody-mode group "fg" value to a color you'd like to use for that particular mode, and the plugin should pick that up. If that doesn't work, try setting your colorscheme as a dependency for Moody.

If the groups are defined, they will take precedence over color option in config. 

But you can instead omit the highlight-group-part altogether, and just use the color option in config, if that is more convenient :-) (at least you should be able to now that I fixed the bug you reported, thx again!)

**Comment by kamack38** [comment]
The update has fixed the issue. Closing...
